### PR TITLE
fix: restyle mainpage

### LINKED ISSUE #35: Hide unusable actions
image

Not sure what better, can ask feedback to others, but maybe can hide issue / revoke as long as no document store is set

### PR DESCRIPTION
**Pull request by ChenRen93**
Closes #35

### CODE REVIEW

File: src/page/main-page.tsx [hunk 1]
```diff
@@ -66,7 +79,51 @@ export const MainPage: FunctionComponent = () => {
...
+
+      {documentStoreStatus && activeFeatureBlock === "issue-revoke" && activeSubFeatureBlock === "revoke" && (
+        <RevokeBlock documentStoreAddress={documentStoreAddress} />
+      )}
+
+      {documentStoreStatus && activeFeatureBlock === "issue-revoke" && activeSubFeatureBlock === "issue" && (
+        <IssueBlock documentStoreAddress={documentStoreAddress} />
+      )}
+
+      {/* <hr className={`mt-16 max-w-screen-lg w-full mx-auto px-4`} /> */}
```
Comment (Nebulis) [inline src/page/main-page.tsx:125]: delete commented code

Comment (ChenRen93) [reply src/page/main-page.tsx]: done.

**Review by Nebulis — APPROVED** [review]
