### PR TITLE
fix: rename-files

### LINKED ISSUE #17: Rename ALL files to follow kebab-case
I said all, unless lib limitation :)

### PR DESCRIPTION
**Pull request by ChenRen93**
Closes #17

### CODE REVIEW

File: src/App.tsx [hunk 1]
```diff
@@ -1,8 +1,8 @@
 declare let window: any;
```
Comment (Nebulis) [inline src/App.tsx:1]: App => app :)

Comment (Nebulis) [reply src/App.tsx:1]: and css file

**Review by Nebulis — APPROVED** [review]
